version: '3.8'

services:
  db:
    container_name: pg_container
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: DataScienceDB
      POSTGRES_USER: ftovar
      POSTGRES_PASSWORD: secret
      PGDATA: /var/lib/postgresql/data
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: secret
      PGADMIN_LISTN_PORT: 80
    ports:
      - "5050:80"
    volumes:
      - pgadmindata:/var/lib/pgadmin
    links:
      - "db:pgsql-server"

volumes:
    pgdata:
    pgadmindata: